# REAL ROBOT

#Kp_linear_: 30
#Kp_yaw_: 60
#Kp_pitch_: 335
#Kd_linear_: 170
#Kd_yaw_: 50
#Kd_pitch_: 135

###################

# RVIZ

#Kp_linear_: 5
#Kp_yaw_: 5
#Kp_pitch_: 10

#Kd_linear_: 7
#Kd_yaw_: 7
#Kd_pitch_: 10

####################


#Kp_rarm1_: 300
#Kp_rarm2_: 300
#Kp_rarm3_: 300
#Kp_rarm4_: 300
#Kp_rarm5_: 300

#Kp_larm1_: 300
#Kp_larm2_: 300
#Kp_larm3_: 300
#Kp_larm4_: 300
#Kp_larm5_: 300

#Kd_rarm1_: 150
#Kd_rarm2_: 150
#Kd_rarm3_: 150
#Kd_rarm4_: 150
#Kd_rarm5_: 150

#Kd_larm1_: 150
#Kd_larm2_: 150
#Kd_larm3_: 150
#Kd_larm4_: 150
#Kd_larm5_: 150

#Kp_rarm_pitch_shoulder_: 700
#Kd_rarm_pitch_shoulder_: 100

#Kp_larm_pitch_shoulder_: -700
#Kd_larm_pitch_shoulder_: -100


#Kp_rarm_pitch_elbow_: 800
#Kd_rarm_pitch_elbow_: 100

#Kp_larm_pitch_elbow_: -800
#Kd_larm_pitch_elbow_: -100

####################

# RVIZ

# Kp_rarm1_: 50
# Kp_rarm2_: 50
# Kp_rarm3_: 24
# Kp_rarm4_: 50
# Kp_rarm5_: 21

# Kp_larm1_: 50
# Kp_larm2_: 50
# Kp_larm3_: 24
# Kp_larm4_: 50
# Kp_larm5_: 21

# Kd_rarm1_: 8
# Kd_rarm2_: 7
# Kd_rarm3_: 7
# Kd_rarm4_: 8
# Kd_rarm5_: 7

# Kd_larm1_: 8
# Kd_larm2_: 7
# Kd_larm3_: 7
# Kd_larm4_: 8
# Kd_larm5_: 7

# Kp_rarm_pitch_shoulder_: 130
# Kd_rarm_pitch_shoulder_: 10

# Kp_larm_pitch_shoulder_: -130
# Kd_larm_pitch_shoulder_: -10


# Kp_rarm_pitch_elbow_: 50
# Kd_rarm_pitch_elbow_: 10

# Kp_larm_pitch_elbow_: -50
# Kd_larm_pitch_elbow_: -10

#####################

# REAL ROBOT

Kp_linear_: 30
Kp_yaw_: 60
Kp_pitch_: 335
Kd_linear_: 170
Kd_yaw_: 50
Kd_pitch_: 135

Kp_rarm1_: 300
Kp_rarm2_: 300
Kp_rarm3_: 300
Kp_rarm4_: 300
Kp_rarm5_: 300

Kp_larm1_: 300
Kp_larm2_: 300
Kp_larm3_: 300
Kp_larm4_: 300
Kp_larm5_: 300

Kd_rarm1_: 150
Kd_rarm2_: 150
Kd_rarm3_: 150
Kd_rarm4_: 150
Kd_rarm5_: 150

Kd_larm1_: 150
Kd_larm2_: 150
Kd_larm3_: 150
Kd_larm4_: 150
Kd_larm5_: 150

Kp_rarm_pitch_shoulder_: 700
Kd_rarm_pitch_shoulder_: 100

Kp_larm_pitch_shoulder_: -700
Kd_larm_pitch_shoulder_: -100


Kp_rarm_pitch_elbow_: 800
Kd_rarm_pitch_elbow_: 100

Kp_larm_pitch_elbow_: -800
Kd_larm_pitch_elbow_: -100

#####################################


