## Namespace of the robot
namespace: "AlterEgo"

## Sample time
T_sample: 0.01

## Number of qbAdvance Motors
joints_number: 10

## Joints name
joints_name: 
 - "base_to_left_shoulder"
 - "shoulder_to_left_arm"
 - "arm_to_left_elbow"
 - "elbow_to_left_forearm"
 - "forearm_to_left_EE"
 - "base_to_right_shoulder"
 - "shoulder_to_right_arm"
 - "arm_to_right_elbow"
 - "elbow_to_right_forearm"
 - "forearm_to_right_EE"
 
# topic names to which publish the references 
ref1_topic_name: 
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'
 - '/reference_1'

# ref1_topic_name: 
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'
#  - '/link_command'

ref2_topic_name: 
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'
 - '/reference_2'


